name: flat_on_fire
description: A new Flutter project to create the Flat Out Management application, using Firebase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  get_it: ^7.2.0
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3
  get_it_mixin: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/