name: flat_on_fire
description: A new Flutter project to create the Flat Out Management application, using Firebase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  get_it: ^7.2.0
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3
  get_it_mixin: ^3.1.4
  firebase_app_check: ^0.0.6+13
  cloud_firestore: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic
          style: italic
          weight: 900
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100