name: flat_on_fire
description: A new Flutter project to create the Flat Out Management application, using Firebase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.2"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_app_check: ^0.0.6
  firebase_core: ^1.17.1
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
  google_sign_in: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway/Raleway-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway/Raleway-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/Raleway-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway/Raleway-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway/Raleway-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway/Raleway-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway/Raleway-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway/Raleway-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
          weight: 100