name: flat_on_fire
description: A new Flutter project to create the Flat Out Management application, using Firebase.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.2"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_app_check: ^0.0.6
  firebase_core: ^1.17.1
  google_sign_in: ^5.3.3
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather/Merriweather-Black.ttf
          weight: 900
        - asset: fonts/Merriweather/Merriweather-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: fonts/Merriweather/Merriweather-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Merriweather/Merriweather-Regular.ttf
          weight: 400
        - asset: fonts/Merriweather/Merriweather-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Merriweather/Merriweather-Light.ttf
          weight: 300
        - asset: fonts/Merriweather/Merriweather-LightItalic.ttf
          style: italic
          weight: 300
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
          style: italic
          weight: 300
