// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomGUFNv_Re7tYblQBewi2hlMCg8teTO4',
    appId: '1:381231754472:android:7b879185d9c822a481ad5d',
    messagingSenderId: '381231754472',
    projectId: 'flat-on-fire-services',
    storageBucket: 'flat-on-fire-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdH-mFHcus8R3Js32naQjb2gdQALpEDTA',
    appId: '1:381231754472:ios:1b9530a99ba1f53e81ad5d',
    messagingSenderId: '381231754472',
    projectId: 'flat-on-fire-services',
    storageBucket: 'flat-on-fire-services.appspot.com',
    androidClientId: '381231754472-0tf125saej5jbn4g0bs9tid50gpk5ci3.apps.googleusercontent.com',
    iosClientId: '381231754472-dqppaa200kn4slqlnnd7nr00cuuhehq2.apps.googleusercontent.com',
    iosBundleId: 'com.honsoncooky.flatOnFire',
  );
}
